# frozen_string_literal: true

require "date"
require_relative "docs_contract"

# Shared catalog for the GitHub Pages site. `llms.txt` link lists and
# `sitemap.xml` are generated from this list so they cannot drift.
module MutineerSiteDocs
  # Public origin for every published docs URL.
  BASE = "https://davidteren.github.io/mutineer"

  # One published path and how it appears in agent indexes.
  Entry = Data.define(:path, :section, :title, :blurb, :priority, :llms)

  # Published Pages files. `:docs` / `:optional` match `llms.txt` sections.
  # `llms: false` still appears in the sitemap (the index file itself).
  CATALOG = [
    Entry.new("/", :docs, "Overview, operators, and usage",
      "what Mutineer is, the mutation operators, install, and CLI flags.", "1.0", true),
    Entry.new("/agentic-coding.html", :docs, "For AI agents & CI",
      "the agent inner loop, CI regression gating, the GitHub Action, and equivalent-mutant suppression.", "0.8", true),
    Entry.new("/json-schema.html", :docs, "JSON report schema",
      "the versioned JSON contract — `summary`, `survivors[]`, `ignored[]`, and `baseline` blocks.", "0.8", true),
    Entry.new("/api/", :docs, "Ruby API (YARD)",
      "class reference generated from this checkout — tracks the shipped gem.", "0.7", true),
    Entry.new("/sample-report.html", :docs, "Sample HTML report",
      "example report data displayed in the website theme; the CLI’s self-contained HTML output has a different presentation.", "0.5", true),
    Entry.new("/llms-full.txt", :optional, "Full docs as one file",
      "README + agent/CI guide + JSON schema concatenated for LLM ingestion.", "0.4", true),
    Entry.new("/skill.md", :optional, "Agent skill",
      "compact skill card — install, the agent loop, exit codes, and links.", "0.4", true),
    Entry.new("/index.md", :optional, "Landing page (Markdown)",
      "homepage / CLI essentials twin of the HTML landing page.", "0.6", true),
    Entry.new("/agentic-coding.md", :optional, "Agent & CI guide (Markdown)",
      "Markdown twin of the agent inner-loop and CI recipes.", "0.5", true),
    Entry.new("/json-schema.md", :optional, "JSON schema (Markdown)",
      "Markdown twin of the JSON report schema reference.", "0.5", true),
    Entry.new("/agents.txt", :optional, "Agent access policy",
      "read-only access policy and pointers at `llms.txt` / `sitemap.xml`.", "0.3", true),
    Entry.new("/llms.txt", :optional, "Docs index for agents",
      "the `llms.txt` index this file is.", "0.3", false)
  ].freeze

  # HTML pages that have a same-stem `.md` twin (advertise via rel=alternate).
  HTML_MARKDOWN_TWINS = {
    "docs/index.html" => "index.md",
    "docs/agentic-coding.html" => "agentic-coding.md",
    "docs/json-schema.html" => "json-schema.md"
  }.freeze

  class << self
    # Absolute published URL for a catalog path.
    #
    # @param path [String]
    # @return [String]
    def loc(path)
      "#{BASE}#{path}"
    end

    # Catalog entries that belong in `llms.txt` (excludes the index file itself).
    #
    # @return [Array<Entry>]
    def llms_entries
      CATALOG.select(&:llms)
    end

    # Render `sitemap.xml` from the catalog.
    #
    # lastmod is today on each generate (a refresh). `docs:check` compares
    # locs and priorities only, so a later day does not fail CI.
    #
    # @return [String]
    def sitemap_xml
      stamp = Date.today.iso8601
      rows = CATALOG.map do |entry|
        <<~URL
          <url>
            <loc>#{loc(entry.path)}</loc>
            <lastmod>#{stamp}</lastmod>
            <priority>#{entry.priority}</priority>
          </url>
        URL
      end
      <<~XML
        <?xml version="1.0" encoding="UTF-8"?>
        <!-- Generated by rake docs:generate from rake/site_docs.rb. Do not edit by hand. -->
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        #{rows.join.rstrip}
        </urlset>
      XML
    end

    # Markdown list for one `llms.txt` section.
    #
    # @param section [Symbol]
    # @return [String]
    def llms_section(section)
      llms_entries.select { |e| e.section == section }.map do |entry|
        "- [#{entry.title}](#{loc(entry.path)}): #{entry.blurb}"
      end.join("\n")
    end

    # `llms.txt` with generated Docs / Optional lists.
    #
    # @param source [String]
    # @return [String]
    def llms_txt(source)
      text = replace_section(source, "docs", llms_section(:docs))
      replace_section(text, "optional", llms_section(:optional))
    end

    # Write generated site files in `docs/`.
    #
    # `sitemap.xml` is a Pages build artifact (`rake site:build`), not a
    # committed copy — this only touches `docs/llms.txt` and the contract
    # splices.
    #
    # @return [void]
    def generate!
      write!("docs/llms.txt", llms_txt(File.read("docs/llms.txt")))
      DocsContract.generate!
    end

    # Committed paths whose bytes differ from a fresh generate.
    #
    # @return [Array<String>]
    def stale_files
      stale = []
      stale << "docs/llms.txt" unless File.read("docs/llms.txt") == llms_txt(File.read("docs/llms.txt"))
      stale.concat(DocsContract.stale_files)
      stale
    end

    private

    # Replace a `<!-- site-catalog:NAME -->` … `<!-- /site-catalog:NAME -->` block.
    #
    # @param text [String]
    # @param name [String]
    # @param body [String]
    # @return [String]
    def replace_section(text, name, body)
      start = "<!-- site-catalog:#{name} -->"
      stop = "<!-- /site-catalog:#{name} -->"
      pattern = /#{Regexp.escape(start)}.*?#{Regexp.escape(stop)}/m
      raise "docs/llms.txt is missing #{start} … #{stop}" unless text.match?(pattern)

      text.sub(pattern, "#{start}\n#{body.chomp}\n#{stop}")
    end

    # Write + trailing newline.
    #
    # @param path [String]
    # @param contents [String]
    # @return [void]
    def write!(path, contents)
      File.write(path, contents.end_with?("\n") ? contents : "#{contents}\n")
    end
  end
end
